env:
  global:
  - secure: F2L3RhetOsdnZyKt+UTAhWeL033oECKZW8MXEC09WmoVgol/jDG+OloT12Fq85LLIDym9ti4HKyaMkoEHZCPeK9onBfOBNB4SaFnjb2YGCxNsnSScUTQAqvLVQxBo/7FcAIHzvrWY5t/LltI0CuHdu352177AcXjc7GH4fTuaQRxkqivunAqnhaxwcJse61l/4sdjhvfluvnyuBDzvVWpYshb64BcDcfIy7bk6u3MMNzJl4g1xt8o6ymemUFe2Swl4VPwkAFT4Lt+DBO0GzDowTrziaTe9U03sNWSj96yA792Yped2mm2bOZgr1qr281TNDYzxV4FVzYuVSzcyVbUmoxdXRwBXFxDXtPNSML24Pkmlv7GUi3z8/PbbWTuaj7zmKn95hpU4DcmB7oPYoWmpuAg4HF8k0guvBsyiDWOVj/ZC/oBf5Qh6ruwy5J4K89VyLsCcFMEXtHieqNcoGwpPjlq57W2BNfKWdKI7V4biENU0l/ttSWUbxuxyBY/yhYWLXYxPYeYCk14P3ot3KOVvQ1AEwKizVoc8+zkaCFP+oufLSd4u4n8VzoQXuEC9KSxmK/6aSgvZJfOt0YyPyV5YLzQmdjQhnqixsmZiVsjHYABvTFfSqzj/0svsOwUd+MsYBHdCUKPwBIp6oF7XbJOVQ/YbQ23QQV1myykp46dGI=
  - secure: qeIkFETk6h+DlAFAtWpnbU2XX/0phOht5MMSpxz0hBLfvEhPmT0aCORjYVxPiRhrQoqYKtINyyMgPzKsZjyxWmN3qfTX5zksJ3y58GdBfXR7VQ/66VH70SX+I4fZLnvqiwhmyaIuiEOHZ/crkcfF/AOB6dO+DiLctPpswut/zBb+JjWf6wp2wxXUbhxKM/rFCv2eradA7Xrkg0LNWysJBH6hryOzPl1sDMpxT4NmVgdnhIpiZTOjC6XDW3TfbCHi0MzBDDnzai4pHy39pq0ScFLV6diOSzS2bRGpg982HfujAhPulcBv2UI5xcI7InDjoGctsfMJz9hFLWJ6vnA4ho2JRN0iP6rkdNK5kbmZkVa4KXMT6G0MkIqBNFc6fHSJ4K2sScAnIbplpZD77whRRS1pVBlohDwv6zkEoKT97FmHjflj8j6gHcoHW0mHvEJyOlufFfw4f4a45b/rf+fulLOCBLbVclLb9Bpljd4abkasopR0m0h1RMRPQyH5FYRoYQy563dv4W91dyiVQwHRhaE05bzeiwrhva+fWS/l0Sc/ZtCfGQBxXzoMmQ0F5ypxnoTp7D9pE8zNoFOeXjPYDAGNgFkxJMvd20sj+2QuR6gRkGRYdeXI0mB5rqYHq25rcZQR+Sd4MGr3fGj3BM2xdulGmSCl1edm9zXVle8keq0=
  - secure: PQRFJTCD7FOksb1s+oSMCHmWyhjYYcGqncZzZ3QOYihsXSaTBzl3Pz+2Id/3sv3Q8/AZ0ef3UmcmSxXSj2OJ57tequU9feldpFSSAOP1vY3FqonCAXG5MK39albQb/YhwfMSOiTK56rdP4hIqvcx6rYnpW8JTPVFiMNbAe/68GnZcmncdStk5mKgFbiN1JLKCQ5U6HG42srQ2YNgE47fJaVTo/BxL/LCXVm4NbdnnwdVoAtamT8/j3EExMQ+QOKjo0f0Qyfs+p8DifwsJykbP0BbTy0vmUsWXkNR8PM0LNBdIwtMryWIBfj7UpSQjty7qX7cYD3qb9ujptGvQVhplskty1bmVhAVbPsJ7Remyo8fJXWL2+JlcXvQzxmy85LdmBgRC2qu8u3dw9CL3NDZyEPtLoe5PnLVQ8gSebpHTrIqmQwQcAsL3CKZUXU+PEd2LkGJzH5ilmvdzFG0j+OR/0SyDcLiIYPOgGw2/GMnYgFIE7Zj92AqdZeyxLLBU1VWP+YQhPMquo+5pb5UcaqP+phswH9vWfdAN/WH4VNeolIdq1oMSOXIuzaSoQfUonYbUf9t8S7V7QUZgN8LRBtUnlC1X2m72I4YOHwcBogc77GuHFIacRDGI+0ZVAt+omxslyk6T/PMrWyizTjHWWJDQETnub0nE+ZU5P2uNkirYag=

language: java

jdk:
  - oraclejdk8


before_deploy:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis-ci/pubring.gpg.enc -out .travis-ci/pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis-ci/secring.gpg.enc -out .travis-ci/secring.gpg -d

deploy:
  script: mvn deploy --settings .travis-ci/settings.xml -P release
  on:
    repo: hexagonoframework/hexagono-parent
    branch: master
    jdk: oraclejdk8
